package helpers

// subscription channels
const (
	USERCREATED         = "USERCREATED"
	USERLOGGEDIN        = "USERLOGGEDIN"
	SENDOTP             = "SENDOTP"
	VERIFYEMAIL         = "VERIFYEMAIL"
	UPDATEPHONENUMBER   = "UPDATEPHONENUMBER"
	EMAILVERIFED        = "EMAILVERIFED"
	PHONENUMBERVERIFIED = "PHONENUMBERVERIFIED"
	PRODUCTADDED        = "PRODUCTADDED"
)
